name: tethering
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - xarray
  - numpy
  - netcdf4
  - matplotlib
  - nc-time-axis
  # --- dev / test ---
  - pytest>=8
  - pytest-cov
  - pytest-mock
  - pip:
      - black
      - jinja2
      - -e .